# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xuanchuan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsmake',
            name='accept_user',
        ),
        migrations.RemoveField(
            model_name='itemsreceive',
            name='accept_user',
        ),
        migrations.RemoveField(
            model_name='messagedraft',
            name='accept_user',
        ),
        migrations.AddField(
            model_name='draftbase',
            name='accept_user',
            field=models.ManyToManyField(related_name='accept_user', to=settings.AUTH_USER_MODEL, verbose_name='接受人'),
        ),
    ]
