# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xuanchuan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_count', models.IntegerField(verbose_name='电视媒体类')),
                ('internet_count', models.IntegerField(verbose_name='网络媒体类')),
                ('lift_count', models.IntegerField(verbose_name='电梯海报类')),
                ('news_count', models.IntegerField(verbose_name='新闻媒体类')),
                ('webo_count', models.IntegerField(verbose_name='微博微信类')),
                ('other_count', models.IntegerField(verbose_name='其他')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
