# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('wait', '待审批'), ('success', '已审批')], default='wait', max_length=10, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='messagedraft',
            name='status',
            field=models.CharField(choices=[('wait', '待审批'), ('success', '已审批')], default='wait', max_length=10, verbose_name='状态'),
        ),
    ]
