# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('停用', '停用'), ('启用', '启用')], default='启用', max_length=5, verbose_name='状态'),
        ),
    ]
