# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0002_auto_20170614_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedraft',
            name='style',
        ),
        migrations.AddField(
            model_name='draftbase',
            name='style',
            field=models.CharField(default='', max_length=20, verbose_name='表单申请申请'),
        ),
    ]
