# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0002_categorycount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycount',
            name='internet_count',
            field=models.IntegerField(default=0, verbose_name='网络媒体类'),
        ),
        migrations.AlterField(
            model_name='categorycount',
            name='lift_count',
            field=models.IntegerField(default=0, verbose_name='电梯海报类'),
        ),
        migrations.AlterField(
            model_name='categorycount',
            name='news_count',
            field=models.IntegerField(default=0, verbose_name='新闻媒体类'),
        ),
        migrations.AlterField(
            model_name='categorycount',
            name='other_count',
            field=models.IntegerField(default=0, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='categorycount',
            name='tv_count',
            field=models.IntegerField(default=0, verbose_name='电视媒体类'),
        ),
        migrations.AlterField(
            model_name='categorycount',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='categorycount',
            name='webo_count',
            field=models.IntegerField(default=0, verbose_name='微博微信类'),
        ),
    ]
