# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0002_auto_20170612_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='style',
            field=models.CharField(default='', max_length=10, verbose_name='表类型'),
        ),
    ]
