# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0003_auto_20170622_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmake',
            name='require_time',
            field=models.CharField(default='', max_length=20, verbose_name='要求完成时间'),
        ),
    ]
