# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0003_auto_20170615_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('stop', '停用'), ('active', '启用')], default='active', max_length=6, verbose_name='状态'),
        ),
    ]
