# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xuanchuan', '0003_items_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('status', models.CharField(choices=[('wait', '待审批'), ('success', '已审批')], default='wait', max_length=10, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='xc/files/%Y/%m', verbose_name='附件')),
                ('sum_cost', models.FloatField(verbose_name='总费用')),
                ('accept_user', models.ManyToManyField(related_name='itemsmake_accept_user', to=settings.AUTH_USER_MODEL, verbose_name='接受人')),
                ('draft_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='起草人')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.Opinion', verbose_name='领导意见')),
            ],
            options={
                'verbose_name': '宣传资料制作',
                'verbose_name_plural': '宣传资料制作',
            },
        ),
        migrations.CreateModel(
            name='ItemsReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('status', models.CharField(choices=[('wait', '待审批'), ('success', '已审批')], default='wait', max_length=10, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='xc/files/%Y/%m', verbose_name='附件')),
                ('accept_user', models.ManyToManyField(related_name='itemsreceive_accept_user', to=settings.AUTH_USER_MODEL, verbose_name='接受人')),
                ('draft_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='起草人')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.Opinion', verbose_name='领导意见')),
            ],
            options={
                'verbose_name': '宣传资料制作',
                'verbose_name_plural': '宣传资料制作',
            },
        ),
        migrations.RemoveField(
            model_name='items',
            name='accept_user',
        ),
        migrations.RemoveField(
            model_name='items',
            name='draft_user',
        ),
        migrations.RemoveField(
            model_name='items',
            name='opinion',
        ),
        migrations.AlterField(
            model_name='itemmake',
            name='lis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.ItemsMake', verbose_name='宣传资料制作表'),
        ),
        migrations.AlterField(
            model_name='needitem',
            name='lis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.ItemsReceive', verbose_name='宣传资料领用表'),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
