# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0003_auto_20170614_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedraft',
            name='main',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.DraftBase', verbose_name='基础信息'),
        ),
    ]
