# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0003_auto_20170608_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedraft',
            name='end_time',
            field=models.CharField(default='', max_length=20, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='messagedraft',
            name='start_time',
            field=models.CharField(default='', max_length=20, verbose_name='开始时间'),
        ),
    ]
