# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0004_auto_20170614_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftbase',
            name='style',
            field=models.CharField(default='', max_length=20, verbose_name='表单申请类型'),
        ),
        migrations.AlterField(
            model_name='itemsmake',
            name='main',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.DraftBase', verbose_name='基础信息'),
        ),
        migrations.AlterField(
            model_name='itemsreceive',
            name='main',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.DraftBase', verbose_name='基础信息'),
        ),
    ]
