# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuanchuan', '0004_auto_20170608_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedraft',
            name='style',
            field=models.CharField(default='宣传信息申请', max_length=20, verbose_name='宣传信息申请'),
        ),
    ]
