# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xuanchuan', '0004_auto_20170615_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMakeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_count', models.IntegerField(default=0, verbose_name='手册')),
                ('adv_count', models.IntegerField(default=0, verbose_name='广告')),
                ('video_count', models.IntegerField(default=0, verbose_name='视频')),
                ('leaflet_count', models.IntegerField(default=0, verbose_name='单张')),
                ('other_count', models.IntegerField(default=0, verbose_name='其他')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '宣传物资领用统计',
                'verbose_name_plural': '宣传物资领用统计',
            },
        ),
        migrations.CreateModel(
            name='ItemReceiveCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_count', models.IntegerField(default=0, verbose_name='手册')),
                ('badge_count', models.IntegerField(default=0, verbose_name='胸章')),
                ('pendant_count', models.IntegerField(default=0, verbose_name='吊坠')),
                ('ticket_count', models.IntegerField(default=0, verbose_name='电影票')),
                ('other_count', models.IntegerField(default=0, verbose_name='其他')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '宣传物资领用统计',
                'verbose_name_plural': '宣传物资领用统计',
            },
        ),
        migrations.AlterModelOptions(
            name='categorycount',
            options={'verbose_name': '宣传信息发布统计', 'verbose_name_plural': '宣传信息发布统计'},
        ),
    ]
