# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default='', max_length=11, verbose_name='电话'),
        ),
    ]
