# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xuanchuan', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.DraftBase', verbose_name='主表'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='opinion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.Opinion', verbose_name='领导意见'),
        ),
        migrations.AddField(
            model_name='addscheme',
            name='lis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Scheme', verbose_name='方案表'),
        ),
    ]
