# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170622_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='opinion',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.Opinion', verbose_name='领导意见'),
        ),
    ]
