# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropagatePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_timestyle', models.CharField(default='', max_length=10, verbose_name='计划时间类别')),
                ('blame_person', models.CharField(max_length=10, verbose_name='负责人')),
                ('plan_time', models.CharField(default='', max_length=20, verbose_name='计划时间')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='xc/files/%Y/%m', verbose_name='附件')),
            ],
            options={
                'verbose_name': '宣传计划申请',
                'verbose_name_plural': '宣传计划申请',
            },
        ),
        migrations.CreateModel(
            name='WorkTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default='', verbose_name='申请时间')),
                ('work_target', models.CharField(max_length=200, verbose_name='工作指标')),
                ('finish_time', models.CharField(default='', max_length=20, verbose_name='完成时间')),
                ('finish_number', models.IntegerField(default='', verbose_name='完成次数')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='xc/files/%Y/%m', verbose_name='附件')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('propagate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.PropagatePlan', verbose_name='计划表')),
            ],
        ),
    ]
