# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropagatePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(default='宣传计划申请', max_length=20, verbose_name='宣传计划申请')),
                ('blame_person', models.CharField(max_length=10, verbose_name='负责人')),
                ('plan_time', models.CharField(default='', max_length=20, verbose_name='计划时间')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='xc/files/%Y/%m', verbose_name='附件')),
            ],
            options={
                'verbose_name': '宣传计划申请',
                'verbose_name_plural': '宣传计划申请',
            },
        ),
    ]
