# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20170614_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propagateplan',
            name='accept_user',
        ),
    ]
