# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_remove_propagateplan_accept_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propagateplan',
            name='style',
        ),
    ]
