# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 02:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0004_remove_propagateplan_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default='', verbose_name='申请时间')),
                ('work_target', models.CharField(max_length=200, verbose_name='工作指标')),
                ('finish_time', models.CharField(default='', max_length=20, verbose_name='完成时间')),
                ('finish_number', models.IntegerField(default='', verbose_name='完成次数')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='xc/files/%Y/%m', verbose_name='附件')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='propagateplan',
            name='main',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xuanchuan.DraftBase', verbose_name='基础信息'),
        ),
        migrations.AlterField(
            model_name='propagateplan',
            name='office',
            field=models.ManyToManyField(to='users.Office', verbose_name='小组'),
        ),
        migrations.AddField(
            model_name='worktarget',
            name='propagate_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.PropagatePlan', verbose_name='计划表'),
        ),
        migrations.AddField(
            model_name='worktarget',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL, verbose_name='填指标者'),
        ),
    ]
