# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20170615_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='propagateplan',
            name='plan_timestyle',
            field=models.CharField(default='', max_length=10, verbose_name='计划时间类别'),
        ),
    ]
